$(function(){
	$(window).ready(function(){
		$(document).scrollTop(0)
	})
	if($(document).scrollTop()>=0){
		$('.user').css('transform','translate3d(0,0,0)')
		$('.user').animate({opacity:'1'},100)
		$('.join>h2').css('transform','translate3d(0,0,0)')
		$('.join>h2').animate({opacity:'1'},100)
		$('.join>p').css('transform','translate3d(0,0,0)')
		$('.join>p').animate({opacity:'1'},100)
	}
	$(window).scroll(function(){
		console.log($(document).scrollTop())
		if($(document).scrollTop()>300){
			$('.ls-main>h2').css('transform','translate3d(0,0,0)')
			$('.ls-main>h2').animate({opacity:'1'},1)
			$('.ls-main>p').css('transform','translate3d(0,0,0)')
			$('.ls-main>p').animate({opacity:'1'},1)
		}
		if($(document).scrollTop()>500){
			$('.tab-content').css('transform','scale(1)')
		}
		if($(document).scrollTop()>1300){
			$('.news-main>h2').css('transform','translate3d(0,0,0)')
			$('.news-main>h2').animate({opacity:'1'},1)
			$('.news-main>p').css('transform','translate3d(0,0,0)')
			$('.news-main>p').animate({opacity:'1'},1)
			$('.news-main>ul>li').css('transform','translate3d(0,0,0)')
			$('.news-main>ul>li').animate({opacity:'1'},1)
		}
		if($(document).scrollTop()>2000){
			$('.about>h2').css('transform','translate3d(0,0,0)')
			$('.about>h2').animate({opacity:'1'},1)
			$('.about>p').css('transform','translate3d(0,0,0)')
			$('.about>p').animate({opacity:'1'},1)
			$('.ab-main>img').css('transform','translate3d(0,0,0)')
			$('.ab-main>img').animate({opacity:'1'},1)
		}
	})
})